apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
 name: my-demo-app
description: main application pipeline
serialPipeline:
 stages:
 - targetId: qsprod
   profiles: []
 - targetId: qsprod-eu
   profiles: []

---


apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: qsprod
description: production cluster
gke:
 cluster: projects/gkemedium/locations/us-central1/clusters/cluster-1

---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: qsprod-eu
description: production cluster eu
gke:
 cluster: projects/gkemedium/locations/us-central1/clusters/cluster-eu